# Generated by Django 4.2.2 on 2023-06-24 19:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_menuitem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MenuItem",
        ),
    ]
